stages:
  - deploy
  - undeploy

deploy:
  image: harbor-gn2.cicd.s15m.nl/docker-hub-proxy/alpine/helm:latest
  stage: deploy
  environment:
    name: overheid-test4
  script:
    - helm upgrade --install --debug gezag ./ --namespace=bzk-mev-ont

undeploy:
  image: harbor-gn2.cicd.s15m.nl/docker-hub-proxy/alpine/helm:latest
  stage: undeploy
  when: manual
  environment:
    name: overheid-test4
  script:
    - helm uninstall --debug gezag --namespace=bzk-mev-ont
